language: php

git:
  depth: 2

matrix:
  include:
    - php: 5.3
    - php: 5.4
    - php: 5.5
    - php: 5.6
    - php: 7.0
      env:
      - LINT=true COVERAGE=true
    - php: 7.1
      env:
      - LINT=true
    - php: nightly
    - php: hhvm-3.9
      sudo: required
      dist: trusty
      group: edge

  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - source .travis/xdebug.sh
  - xdebug-disable

before_script:
  - travis_retry composer update --no-interaction --prefer-source --prefer-stable

script:
  - if [[ $LINT = true ]]; then
      composer assert:cs-lint;
      ./bin/travis/lint-docs;
      composer require --dev phpstan/phpstan;
      vendor/bin/phpstan analyse --no-progress --ansi -l 5 lib;
    fi
  - if [[ "$COVERAGE" == "true" ]]; then
      xdebug-enable;
      vendor/bin/phpunit vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover;
      xdebug-disable;
    else
      vendor/bin/phpunit;
    fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
